### ISSUE TITLE
Failed to find TTS_URL

### ISSUE THREAD

**Issue by oleteacher** [nicolrx/scraper-youtube-captions#1]
Hello friend.

We are trying to use your script in classroom but getting:

Failed to find TTS_URL in page source for http://www.youtube.com/watch?v=YxI6GV30yL0

Can seem to find why error. I wonder if YouTube changed something on their end?

**Comment by nicolrx** [comment]
Hello there,
Sorry, I don't maintain this repository since quite a long time. However, the error is from the closed-caption.php script, into the _function getBaseClosedCaptionsUrl($videoId)_.

I guess YouTube changed their HTML, and the script can't scrape the subtitles anymore. You can try to find where those are in the source code of the page and try to fix the function. 

Good luck!

**Comment by oleteacher** [comment]
I understand. Thank you for pointing me in the right direction. Might be a good class project 👍 

Wishing you health and safety.
